import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogs App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${inter.className} bg-[#281945] text-white`} suppressHydrationWarning={true}>
        <div className="px-2 md:px-20 py-5">
          <Navbar/>
          {children}
          <Footer/>
        </div>
        </body>
    </html>
  );
}
